@startuml
skinparam linetype ortho

entity tactics {
  * tactic_id : STR
  ---
  stix_id : STR
  tactic : STR
  description_en: STR
  description_jp: STR <<NULL>>
  url: STR
  created : DATE 
  last_modified : DATE
  domein: STR 
  version: STR
  order: INTEGER <<UNIQUE>>
}


entity tac_tech {
  * id : INTEGER
  ---
  tactic_id: STR
  technique_id:  STR
}

entity techniques {
  * technique_id : STR
  ---
  stix_id : STR
  technique : STR
  description_en: STR
  description_jp: STR
  url: STR
  created : DATE
  last_modified : DATE
  domain: STR
  version: STR
  detection: STR
  is_sub_technique: BOOL
  parent_technique: STR
}

entity techdata {
  * id : INTEGER
  ---
  datasource_id: STR
  technique_id:  STR
}

entity datasources {
  * datasource_id : STR
  ---
  datasource : STR
  stix_id : STR
  description_en: STR
  description_jp: STR
  platform: STR
  created : DATE
  last_modified : DATE
  version: STR
  type: STR
  url: STR
}

entity additionaldatasources {
  * datasource_id : STR
  ---
  ' # 0 使用しない、１　使用するかも　２　使用する。
  is_target  <<enum>> 
  
}

entity cyberkillchain {
  * killchain_id : STR
  ---
  order: INTEGER
  phase = STR
  description_en = STR
  description_jp = STR
}

entity collectionlayers {
  * id : INTEGER
  ---
  datasource_id:  STR
  collection_layer: STR  
}

tactics ||--{ tac_tech

techniques ||--{ tac_tech
techniques ||--{ tech_data
datasources ||--{ tech_data

datasources ||--{ collectionlayers
datasources ||--|| additionaldatasources


cyberkillchain ||--{ tactics

' techniques || 

@enduml
