@startuml
skinparam linetype ortho

package "tactic" {

  entity tactics {
    * tactic_id : str
    ---
    stix_id : str
    tactic : str
    description_en: str
    description_jp: str <<NULL>>
    url: str
    created : DATE 
    last_modified : DATE
    domein: str 
    version: str
    order: INTEGER <<UNIQUE>>
  }

  entity cyberkillchain {
    * killchain_id : str
    ---
    order: INTEGER
    phase: str
    description_en: str
    description_jp: str
  }
}

package "datasource" {
  entity datasources {
    * datasource_id : str
    ---
    datasource : str
    stix_id : str
    description_en: str
    description_jp: str
    platform: str
    created : DATE
    last_modified : DATE
    version: str
    type: str
    url: str
  }

  entity additionaldatasources {
    * datasource_id : str
    ---
    ' # 0 使用しない、１　使用するかも　２　使用する。
    is_target  <<enum>>   
  }

  entity datacollection{
    * id : INTERGER
    ---
    datasource_id: str
    collection_layer: CharField()
  }
}


entity tactech {
  * id : INTEGER
  ---
  tactic_id: str
  technique_id:  str
}

entity techniques {
  * technique_id : str
  ---
  stix_id : str
  technique : str
  description_en: str
  description_jp: str
  url: str
  created : DATE
  last_modified : DATE
  domain: str
  version: str
  detection: str
  is_sub_technique: BOOL
  parent_technique: str
}

entity techdata {
  * id : INTEGER
  ---
  datasource_id: str
  technique_id:  str
}

package "Software Package" {
  entity Software{
    software_id: str
    ---
    name: str
    description_en: str
    description_jp: str
    url: str
    created : DATE
    last_modified : DATE
    ' domain
    version: str
    ' platforms
    type: str
  }

  entity SoftwareAlias {
    id: str
    ---
    software_id: str
    alias_name: str
  }
}
entity SoftTech {
  * software_id : str
  * technique_id : str
  ---
}

entity mitigations {
  * mitigation_id : str
  ---
  mitigation: str
  description_en: str
  description_jp: str
  url: str
  created : DATE
  last_modified : DATE
  domain: str
  version: str
}

entity groups {
  * group_id: str
  ---
  + name: str
  description_en: str
  description_jp: str
  url: str
  created: DATE
  last_modified : DATE
  ' domain: STR
  version: str  
}

entity group_software{
  * group_id: str
  * software_id: str
  ---
}


entity techmitigations{
  * id : INTERGER
  ---
  mitigation_id: CharField()
  technique_id: CharField()
}

entity detection{
  * technique_id : str
  * datasource_id : str
  ---
  detection_en: str
  detection_jp: str <<NULL>>
}


groups ||--{ group_software
Software ||--{ group_software

Software ||--{ SoftTech
techniques ||--{ SoftTech

Software ||--{ SoftwareAlias

tactics ||--{ tactech

techniques ||--{ tactech
techniques ||--{ techdata
datasources ||--{ techdata

datasources ||--{ datacollection
datasources ||--|| additionaldatasources

techniques ||--{ techmitigations
mitigations ||--{ techmitigations

techniques ||--{ detection
datasources ||--{ detection


cyberkillchain ||--{ tactics

' techniques || 

@enduml
